# Generated by Django 3.2.4 on 2021-07-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250, null=True)),
                ('dob', models.CharField(max_length=250, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('issuing_authority_name', models.CharField(max_length=250)),
                ('issuing_authority_state', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('file', models.FileField(blank=True, null=True, upload_to='file/')),
            ],
        ),
    ]
